import { Song } from "./song.model";

export const odeToJoy: Song = {
  title: "Ode to Joy",
  notes: [
    [
      { note: "E4", text: "E" },
      { note: "E4", text: "E" },
      { note: "F4", text: "F" },
      { note: "G4", text: "G" },
      { note: "G4", text: "G" },
      { note: "F4", text: "F" },
      { note: "E4", text: "E" },
      { note: "D4", text: "D" },
      { note: "C4", text: "C" },
      { note: "C4", text: "C" },
      { note: "D4", text: "D" },
      { note: "E4", text: "E" },
      { note: "E4", text: "E" },
      { note: "D4", text: "D" },
      { note: "D4", text: "D" },
    ],
    [
      { note: "E4", text: "E" },
      { note: "E4", text: "E" },
      { note: "F4", text: "F" },
      { note: "G4", text: "G" },
      { note: "G4", text: "G" },
      { note: "F4", text: "F" },
      { note: "E4", text: "E" },
      { note: "D4", text: "D" },
      { note: "C4", text: "C" },
      { note: "C4", text: "C" },
      { note: "D4", text: "D" },
      { note: "E4", text: "E" },
      { note: "D4", text: "D" },
      { note: "C4", text: "C" },
      { note: "C4", text: "C" },
    ],
    [
      { note: "D4", text: "D" },
      { note: "D4", text: "D" },
      { note: "E4", text: "E" },
      { note: "C4", text: "C" },
      { note: "D4", text: "D" },
      { note: "E4", text: "E" },
      { note: "F4", text: "F" },
      { note: "E4", text: "E" },
      { note: "C4", text: "C" },
      { note: "D4", text: "D" },
      { note: "E4", text: "E" },
      { note: "F4", text: "F" },
      { note: "E4", text: "E" },
      { note: "D4", text: "D" },
      { note: "C4", text: "C" },
      { note: "D4", text: "D" },
      { note: "G3", text: "G" },
    ],
    [
      { note: "E4", text: "E" },
      { note: "E4", text: "E" },
      { note: "F4", text: "F" },
      { note: "G4", text: "G" },
      { note: "G4", text: "G" },
      { note: "F4", text: "F" },
      { note: "E4", text: "E" },
      { note: "D4", text: "D" },
      { note: "C4", text: "C" },
      { note: "C4", text: "C" },
      { note: "D4", text: "D" },
      { note: "E4", text: "E" },
      { note: "D4", text: "D" },
      { note: "C4", text: "C" },
      { note: "C4", text: "C" },
    ],
  ],
};
